config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get     "login" => :new
    post    "login" => :create
    delete  "logout" => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products do
    get :who_bought, on: :member
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.sum {|item| item.total_price}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_url, status: :see_other, notice: "Your cart is currently empty." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: "Invalid cart"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <h2 class= "font-bold text-lg mb-3" >Your Pragmatic Cart</h2>

  <table class= "table-auto" >
    <%= render cart.line_items%>

    <tfoot>
      <tr>
        <th class= "text-right pr-2 pt-2" colspan= "3" >Total:</th>
        <td class= "text-right pt-2 font-bold border-t-2 border-black" >
        <%= number_to_currency(cart.total_price ) %>
        </td>
      </tr> 
    </tfoot>
  </table>
  
  <div class="flex mt-1">
    <%= button_to "Empty cart", cart, method: :delete, 
    class:"ml-4 rounded-lg py-1 px-2 text-white bg-green-600" %>

    <%= button_to "Checkout", new_order_path, method: :get,
    class:"ml-4 rounded-lg py-1 px-2 text-black bg-green-200" %>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<div class="w-full">
  <p class="text-green-600 px-2 rounded bg-green-100 inline-block mb-3"><%= notice %></p>

  <div id="carts">
    <% @carts.each do |cart| %>
      <%= render cart %>
      <p>
        <%= link_to "Show this cart", cart %>
      </p>
    <% end %>
  </div>

  <%= link_to "New cart", new_cart_path %>
</div>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<div>
  <p class="text-green-600 px-2 rounded-sm bg-green-100 inline-block"><%= notice %></p>

  <%= render @cart %>

  <div class="flex justify-around align-center gap-8 mt-4">
    <%= link_to "Edit this cart", edit_cart_path(@cart) %>
    <%= link_to "Back to carts", carts_path %>

    <%= button_to "Destroy this cart", @cart, method: :delete %>
  </div>
</div>