config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get     "login" => :new
    post    "login" => :create
    delete  "logout" => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products do
    get :who_bought, on: :member
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :title, uniqueness: true, length: {minimum: 10, message: "Title must be at least 10 characters long."}
  validates :image_url, allow_blank: true, format: { with: %r{\.(gif|jpg|png)\z}i, message: "Must be a URL for GIF, JPG or PNG image." }
  validates :price, numericality: {greater_than_or_equal_to: 0.01}

  private
  
    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line Items present')
        throw :abort
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
        
        @product.broadcast_replace_later_to "products", partial:"store/product"
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2>
        <%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:
      </h2>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "input-field" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white
        inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= product.image_url %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<div class="mx-auto px-5 py-5 flex flex-col">
  <h1 class="text-3xl mx-auto">Editing product</h1>

  <div class="mx-auto">
    <%= render "form", product: @product %>
  </div>

  <br>

  <div>
    <%= link_to "Show this product", @product %> |
    <%= link_to "Back to products", products_path %>
  </div>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
      <%= notice %>
    </p>
  <% end %>

  <div class="flex justify-between items-center pb-8">
    <h1 class="mx-auto mt-5 font-bold text-4xl">Products</h1>
  </div>

  <table id="products" class="mx-auto">
    <tfoot>
      <tr>
        <td colspan="3">
          <div class="mt-8">
            <%= link_to 'New product', new_product_path, class: "inline rounded-lg py-3 px-5 bg-green-600 text-white block font-medium" %>
          </div>
        </td>
      </tr>
    </tfoot>

    <tbody>
      <% @products.each do |product| %>
        <tr class="<%= cycle('bg-green-50', 'bg-white') %>">
          <td class="px-2 py-3">
            <%= image_tag(product.image_url, class: 'w-40') %>
          </td>

          <td>
            <h1 class="text-xl font-bold mb-3"><%= product.title %></h1>
            <p>
              <%= truncate(strip_tags(product.description), length: 80) %>
            </p>
          </td>

          <td class="px-3">
            <ul>
              <li>
                <%= link_to 'Show', product, class: 'hover:underline' %>
              </li>
              <li>
                <%= link_to 'Edit', edit_product_path(product), class: 'hover:underline' %>
              </li>
              <li>
                <%= link_to 'Destroy', product, class: 'hover:underline', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              </li>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="mx-auto px-32 py-5 flex flex-col" >
  <h1 class="text-3xl mx-auto">New product</h1>

  <div>
    <%= render "form", product: @product %>
    <%= link_to "Back to products", products_path, class: "rounded-lg py-3 px-5 bg-gray-300 text-black
        inline-block font-medium cursor-pointer" %>
  </div>

</div>

app/views/products/show.html.erb
<div class="flex flex-col">
  <p style="color: green"><%= notice %></p>

  <%= render @product %>

  <div>
    <%= link_to "Edit this product", edit_product_path(@product) %> |
    <%= link_to "Back to products", products_path %>

    <%= button_to "Destroy this product", @product, method: :delete %>
  </div>
</div>