config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get     "login" => :new
    post    "login" => :create
    delete  "logout" => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products do
    get :who_bought, on: :member
  end

end

app/views/layouts/_cart.html.erb
<% if cart and not cart.line_items.empty? %>
  <div id="cart" class="bg-white rounded p-2" >
    <%= render cart %>
  </div>
<% else %>
  <div id="cart"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <header class= "bg-green-700 flex justify-between items-center" >
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf', class:"align-self-start" %>

      <h1> <%# = @page_title %></h1>

      <nav class="flex space-x-4 text-gray-300 leading-8 mr-8">
        <% if session[:user_id]%>
          <%= button_to "Logout", logout_path, method: :delete, class:"block px-4 rounded-md bg-gray-200 text-red-500 font-semibold hover:bg-red-700 hover:text-white transition" %>
        <% else %>
          <%= link_to "Login", login_path, class:"block px-4 rounded-md bg-blue-200 text-slate-900 font-semibold  hover:bg-blue-700 hover:text-blue transition" %>
        <% end %>

      </nav>
    </header>

    <section class= "flex h-screen" >
      <nav class= "bg-green-900 p-6 w-1/4 overflow-y-auto" >

        <ul class="text-gray-300 leading-8 space-y-1">
          <li>
             <a href="/" class="navbar-list-items"> Home </a>
          </li>
          <li>
             <a href="/questions" class="navbar-list-items"> Questions </a>
          </li>

          <li>
             <a href="/news" class="navbar-list-items"> News </a>
          </li>

          <li>
             <a href="/contact" class="navbar-list-items"> Contact </a>
          </li>
        </ul>

        <% if session[:user_id] %>
          <hr class="my-3 border-1 border-gray-300" >

          <ul class="text-gray-300 leading-8">
            <li><%= link_to "Order", orders_path, class:"navbar-list-items" %></li>
            <li><%= link_to "Products", products_path, class:"navbar-list-items" %></li>
            <li><%= link_to "Users", users_path, class:"navbar-list-items" %></li>
          </ul>
        <% end %>

        <hr class="my-3 border-1 border-gray-300" >

        <%= render partial: "layouts/cart", locals: {cart: @cart} %>

      </nav>

      <main class= "container mx-auto mt-4 px-5 flex-grow overflow-y-auto" >
        <%= yield %>
      </main>
    </section>
  </body>
</html>